import {
  createContext,
  useContext,
  useEffect,
  useState,
  type ReactNode,
} from 'react';

export type Language = 'en' | 'km';

type Dict = Record<string, string>;

const en: Dict = {
  'nav.home': 'Home',
  'nav.tools': 'AI Tools',
  'nav.resources': 'Resources',
  'nav.assistant': 'Assistant',
  'nav.pricing': 'Pricing',
  'nav.dashboard': 'Dashboard',
  'nav.admin': 'Admin',
  'nav.signin': 'Sign In',
  'nav.signup': 'Get Started',
  'nav.signout': 'Sign Out',

  'hero.badge': 'The all-in-one AI education platform',
  'hero.title': 'Learn smarter with',
  'hero.title.highlight': 'AI-powered education',
  'hero.subtitle': 'Study, create, and grow with 16+ AI tools, thousands of resources, and a personalized learning experience — all in one beautiful platform.',
  'hero.search.placeholder': 'Search AI tools, courses, documents...',
  'hero.search.button': 'Search',

  'section.featured': 'Featured',
  'section.featured.tools': 'Popular AI Tools',
  'section.latest': 'Latest',
  'section.latest.resources': 'Educational Resources',
  'section.categories': 'Popular Categories',
  'section.categories.desc': 'Explore AI tools by what you need to do',
  'section.features': 'Why choose EDU?',
  'section.features.desc': 'Everything a student needs, beautifully integrated',
  'section.testimonials': 'Student Testimonials',
  'section.testimonials.desc': 'Loved by students around the world',
  'section.faq': 'Frequently Asked Questions',
  'section.contact': 'Get in touch',
  'section.contact.desc': "Have questions? We'd love to hear from you.",

  'common.viewAll': 'View All',
  'common.openTool': 'Open Tool',
  'common.free': 'Free',
  'common.pro': 'Pro',
  'common.premium': 'Premium',
  'common.search': 'Search',
  'common.loading': 'Loading...',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.add': 'Add',
  'common.create': 'Create',
  'common.update': 'Update',
  'common.name': 'Name',
  'common.description': 'Description',
  'common.category': 'Category',
  'common.price': 'Price',
  'common.actions': 'Actions',
  'common.status': 'Status',
  'common.plan': 'Plan',
  'common.role': 'Role',

  'tools.title': 'AI Tools Marketplace',
  'tools.subtitle': 'Browse {count}+ AI tools to supercharge your learning',
  'tools.searchPlaceholder': 'Search tools...',
  'tools.allPlans': 'All plans',
  'tools.topRated': 'Top rated',
  'tools.newest': 'Newest',
  'tools.noResults': 'No tools found. Try a different search or filter.',

  'tool.try': 'Try',
  'tool.run': 'Run',
  'tool.running': 'Running...',
  'tool.result': 'Result',
  'tool.reviews': 'Reviews',
  'tool.dailyLimit': 'Daily limit',
  'tool.usedToday': 'Used today',
  'tool.remainingToday': 'Remaining today',
  'tool.unlimited': 'Unlimited',
  'tool.signUpToUse': 'Sign up to use this tool',
  'tool.upgradeToPro': 'Upgrade to Pro',
  'tool.buyNow': 'Buy Now',
  'tool.purchased': 'Purchased',
  'tool.backToTools': 'Back to Tools',

  'auth.login.title': 'Sign in',
  'auth.signup.title': 'Create your account',
  'auth.login.welcome': 'Welcome back to EDU.',
  'auth.signup.welcome': 'Start learning smarter today.',
  'auth.login.subtitle': 'Welcome back! Please enter your details.',
  'auth.signup.subtitle': 'Free forever. Upgrade anytime.',
  'auth.email': 'Email',
  'auth.password': 'Password',
  'auth.fullName': 'Full name',
  'auth.signIn': 'Sign in',
  'auth.createAccount': 'Create account',
  'auth.orContinue': 'or continue with',
  'auth.haveAccount': "Don't have an account?",
  'auth.noAccount': 'Already have an account?',

  'dashboard.title': 'Dashboard',
  'dashboard.welcome': 'Welcome back',
  'dashboard.totalUses': 'Total AI Uses',
  'dashboard.usedToday': 'Used Today',
  'dashboard.favorites': 'Favorites',
  'dashboard.recentlyUsed': 'Recently Used',
  'dashboard.favoriteTools': 'Favorite Tools',
  'dashboard.notifications': 'Notifications',
  'dashboard.upgradeBanner': 'Unlock unlimited AI',
  'dashboard.upgradeDesc': 'Upgrade to Pro for unlimited usage, premium tools, and priority support.',
  'dashboard.seePlans': 'See plans',
  'dashboard.proMember': 'Pro Member',
  'dashboard.upgradeToPro': 'Upgrade to Pro',

  'admin.title': 'Admin Dashboard',
  'admin.overview': 'Overview',
  'admin.tools': 'Tools',
  'admin.resources': 'Resources',
  'admin.users': 'Users',
  'admin.purchases': 'Purchases',
  'admin.totalUsers': 'Total Users',
  'admin.totalTools': 'Total Tools',
  'admin.totalResources': 'Total Resources',
  'admin.totalRevenue': 'Total Revenue',
  'admin.addTool': 'Add Tool',
  'admin.editTool': 'Edit Tool',
  'admin.addResource': 'Add Resource',
  'admin.editResource': 'Edit Resource',
  'admin.toolName': 'Tool Name',
  'admin.toolSlug': 'Slug',
  'admin.toolIcon': 'Icon',
  'admin.toolCategory': 'Category',
  'admin.toolIsPro': 'Pro Tool',
  'admin.toolUsageLimit': 'Free Usage Limit',
  'admin.toolPrice': 'Price (USD)',
  'admin.toolRating': 'Rating',
  'admin.toolReviews': 'Reviews Count',
  'admin.resourceName': 'Resource Name',
  'admin.resourceType': 'Type',
  'admin.resourceCategory': 'Category',
  'admin.resourceImage': 'Image URL',
  'admin.resourceIsPremium': 'Premium',
  'admin.userEmail': 'Email',
  'admin.userPlan': 'Plan',
  'admin.userRole': 'Role',
  'admin.makeAdmin': 'Make Admin',
  'admin.makeUser': 'Make User',
  'admin.makePro': 'Make Pro',
  'admin.makeFree': 'Make Free',
  'admin.purchaseItem': 'Item',
  'admin.purchaseAmount': 'Amount',
  'admin.purchaseMethod': 'Method',
  'admin.purchaseDate': 'Date',
  'admin.confirmDelete': 'Are you sure you want to delete this?',
  'admin.accessDenied': 'Access denied. Admin only.',
  'admin.saved': 'Saved successfully!',
  'admin.deleted': 'Deleted successfully!',

  'payment.title': 'Complete your purchase',
  'payment.cardNumber': 'Card Number',
  'payment.cardName': 'Cardholder Name',
  'payment.expiry': 'Expiry Date',
  'payment.cvv': 'CVV',
  'payment.payNow': 'Pay Now',
  'payment.processing': 'Processing...',
  'payment.success': 'Payment successful!',
  'payment.cardNumberPlaceholder': '1234 5678 9012 3456',
  'payment.cardNamePlaceholder': 'JOHN DOE',
  'payment.expiryPlaceholder': 'MM/YY',
  'payment.cvvPlaceholder': '123',
  'payment.total': 'Total',
  'payment.secure': 'Your payment is secured with 256-bit encryption',

  'pricing.title': 'Choose your plan',
  'pricing.subtitle': "Start free, upgrade when you're ready. No hidden fees, cancel anytime.",
  'pricing.badge': 'Simple, transparent pricing',
  'pricing.guest': 'Guest',
  'pricing.free': 'Free',
  'pricing.pro': 'Pro',
  'pricing.popular': 'Popular',
  'pricing.currentPlan': 'Current Plan',
  'pricing.payments': 'Accepted payment methods',
  'pricing.paymentsDesc': 'Securely upgrade from Free to Pro with your preferred payment option',
  'pricing.continueWith': 'Continue with',
  'pricing.demoNote': 'Demo only — payment integration requires provider configuration.',

  'footer.tagline': 'The all-in-one AI-powered education platform. Learn, create, and grow with powerful AI tools.',
  'footer.platform': 'Platform',
  'footer.account': 'Account',
  'footer.company': 'Company',
  'footer.rights': 'All rights reserved.',
  'footer.built': 'Developed by IT Students.',

  'stats.tools': 'AI Tools',
  'stats.resources': 'Resources',
  'stats.students': 'Students',
  'stats.countries': 'Countries',
  'stats.purchases': 'Purchases',
  'stats.revenue': 'Revenue',

  'feature.aiLearning.title': 'AI-Powered Learning',
  'feature.aiLearning.desc': '16+ specialized AI tools to help you study, write, code, and research.',
  'feature.aiLearning.cta': 'Explore AI Tools',
  'feature.resources.title': 'Rich Resources',
  'feature.resources.desc': 'Courses, e-books, videos, and exercises — all in one place.',
  'feature.resources.cta': 'Browse Resources',
  'feature.fast.title': 'Fast & Reliable',
  'feature.fast.desc': 'Optimized for speed with instant AI responses and smooth UX.',
  'feature.fast.cta': 'Try AI Assistant',
  'feature.secure.title': 'Secure & Private',
  'feature.secure.desc': 'Row-level security, JWT auth, and encrypted data storage.',
  'feature.secure.cta': 'View Pricing',
  'feature.multilang.title': 'Multi-language Ready',
  'feature.multilang.desc': 'Designed for Khmer, English, Thai, and Vietnamese support.',
  'feature.multilang.cta': 'Get Started',
  'feature.pro.title': 'Pro Experience',
  'feature.pro.desc': 'Unlock unlimited usage, premium tools, and priority support.',
  'feature.pro.cta': 'See Plans',

  'auth.google': 'Google',
  'auth.googleError': 'Google sign-in failed. Please try again.',
  'auth.forgotPassword': 'Forgot password?',
  'auth.resetPassword': 'Send reset link',
  'auth.resetSent': 'Password reset link sent to your email!',

  'admin.code.title': 'Admin Access Code',
  'admin.code.desc': 'Enter the admin access code to continue.',
  'admin.code.placeholder': 'Enter admin code',
  'admin.code.verify': 'Verify',
  'admin.code.invalid': 'Invalid admin code. Please try again.',
  'admin.code.verifying': 'Verifying...',
  'admin.testimonials': 'Testimonials',
  'admin.content': 'Content',
  'admin.addTestimonial': 'Add Testimonial',
  'admin.editTestimonial': 'Edit Testimonial',
  'admin.testimonialName': 'Student Name',
  'admin.testimonialRole': 'Role / Title',
  'admin.testimonialAvatar': 'Avatar URL',
  'admin.testimonialText': 'Testimonial Text',
  'admin.testimonialRating': 'Rating (1-5)',
  'admin.changeCode': 'Change Admin Code',
  'admin.newCode': 'New Admin Code',
  'admin.codeChanged': 'Admin code changed successfully!',
  'admin.totalPurchases': 'Total Purchases',

  'contact.name': 'Name',
  'contact.email': 'Email',
  'contact.message': 'Message',
  'contact.namePlaceholder': 'Your name',
  'contact.emailPlaceholder': 'you@example.com',
  'contact.messagePlaceholder': 'How can we help?',
  'contact.send': 'Send Message',
  'contact.sent': 'Sent!',
  'contact.info.email': 'Email',
  'contact.info.phone': 'Phone',
  'contact.info.address': 'Address',
  'contact.info.emailValue': 'Khouvchvea123@gmail.com',
  'contact.info.phoneValue': '+855 978114331',
  'contact.info.addressValue': 'Phnom Penh, Cambodia',
  'contact.payments': 'Accepted payments',

  'faq.q1': 'What is EDU?',
  'faq.a1': 'EDU is an all-in-one AI-powered education platform where students can learn, access educational resources, and use powerful AI tools.',
  'faq.q2': 'Is EDU free to use?',
  'faq.a2': 'Yes! The Free plan gives you limited daily AI usage and access to free educational content. Upgrade to Pro for unlimited usage and premium features.',
  'faq.q3': 'What is included in the Pro plan?',
  'faq.a3': 'Pro includes unlimited AI usage, premium tools and courses, faster responses, priority support, cloud history, and advanced features.',
  'faq.q4': 'Can I cancel my subscription anytime?',
  'faq.a4': 'Absolutely. You can cancel your Pro subscription at any time and continue using Free plan features.',
  'faq.q5': 'Do I need to create an account?',
  'faq.a5': 'Guests can browse tools and view resources. To use AI tools and save favorites, create a free account.',
  'faq.q6': 'Which payment methods are supported?',
  'faq.a6': 'We support ABA Pay, KHQR, Visa/MasterCard, PayPal, and Stripe for secure upgrades.',

  'pricing.guestDesc': 'For curious visitors',
  'pricing.freeDesc': 'For students starting out',
  'pricing.proDesc': 'For serious learners',
  'pricing.guestFeatures': 'Browse AI tools, View educational resources, Read testimonials',
  'pricing.freeFeatures': 'Limited AI usage per day, Access free educational content, Save favorites, Personal dashboard, Community access',
  'pricing.proFeatures': 'Unlimited AI usage, All premium AI tools, Premium courses & resources, Faster AI response times, Priority support, Cloud history, Advanced features',
  'pricing.signUpFree': 'Sign Up Free',
  'pricing.upgradeToPro': 'Upgrade to Pro',
  'pricing.browseTools': 'Browse Tools',
  'pricing.trustSecure': 'Secure payments',
  'pricing.trustSecureDesc': '256-bit encryption on every transaction',
  'pricing.trustInstant': 'Instant access',
  'pricing.trustInstantDesc': 'Pro features activate immediately',
  'pricing.trustCancel': 'Cancel anytime',
  'pricing.trustCancelDesc': 'No long-term contracts, no hassle',
};

const km: Dict = {
  'nav.home': 'ទំព័រដើម',
  'nav.tools': 'ឧបករណ៍ AI',
  'nav.resources': 'ធនធាន',
  'nav.assistant': 'ជំនួយការ',
  'nav.pricing': 'តម្លៃ',
  'nav.dashboard': 'ផ្ទាំងគ្រប់គ្រង',
  'nav.admin': 'អេដមីន',
  'nav.signin': 'ចូល',
  'nav.signup': 'ចាប់ផ្តើម',
  'nav.signout': 'ចាកចេញ',

  'hero.badge': 'វេទិកាអប់រំដែលមាន AI ទាំងអស់ក្នុងមួយ',
  'hero.title': 'រៀនបានឆ្លាតជាមួយ',
  'hero.title.highlight': 'អប់រំដែលមាន AI',
  'hero.subtitle': 'សិក្សា បង្កើត និងរីកចម្រើនជាមួយឧបករណ៍ AI ជាង ១៦ ប្រភេទ ធនធានរាប់ពាន់ និងបទពិសោធន៍រៀនតាមផ្ទាល់ខ្លួន — ទាំងអស់ក្នុងវេទិកាស្អាតមួយ។',
  'hero.search.placeholder': 'ស្វែងរកឧបករណ៍ AI វគ្គសិក្សា ឯកសារ...',
  'hero.search.button': 'ស្វែងរក',

  'section.featured': 'ពិសេស',
  'section.featured.tools': 'ឧបករណ៍ AI ដែលពេញនិយម',
  'section.latest': 'ថ្មីៗ',
  'section.latest.resources': 'ធនធានអប់រំ',
  'section.categories': 'ប្រភេទដែលពេញនិយម',
  'section.categories.desc': 'ស្វែងរកឧបករណ៍ AI តាមតម្រូវការរបស់អ្នក',
  'section.features': 'ហេតុអ្វីជ្រើសរើស EDU?',
  'section.features.desc': 'អ្វីដែលសិស្សត្រូវការ បង្កប់យ៉ាងស្អាត',
  'section.testimonials': 'មតិសិស្ស',
  'section.testimonials.desc': 'ស្រលាញ់ដោយសិស្សទូទាំងពិភពលោក',
  'section.faq': 'សំណួរដែលសួរញឹកញាប់',
  'section.contact': 'ទាក់ទងមកយើង',
  'section.contact.desc': 'មានសំណួរ? យើងចង់ស្តាប់ពីអ្នក។',

  'common.viewAll': 'មើលទាំងអស់',
  'common.openTool': 'បើកឧបករណ៍',
  'common.free': 'ដោយឥតគិត',
  'common.pro': 'Pro',
  'common.premium': 'ពិសេស',
  'common.search': 'ស្វែងរក',
  'common.loading': 'កំពុងផ្ទុក...',
  'common.save': 'រក្សាទុក',
  'common.cancel': 'បោះបង់',
  'common.delete': 'លុប',
  'common.edit': 'កែសម្រួល',
  'common.add': 'បន្ថែម',
  'common.create': 'បង្កើត',
  'common.update': 'កែប្រែ',
  'common.name': 'ឈ្មោះ',
  'common.description': 'ការពិពណ៌នា',
  'common.category': 'ប្រភេទ',
  'common.price': 'តម្លៃ',
  'common.actions': 'សកម្មភាព',
  'common.status': 'ស្ថានភាព',
  'common.plan': 'ផែនការ',
  'common.role': 'តួនាទី',

  'tools.title': 'ទីផ្សារឧបករណ៍ AI',
  'tools.subtitle': 'មើលឧបករណ៍ AI {count}+ ដែលជួយឲ្យអ្នករៀនបានលឿន',
  'tools.searchPlaceholder': 'ស្វែងរកឧបករណ៍...',
  'tools.allPlans': 'គ្រប់ផែនការ',
  'tools.topRated': 'ពិន្ទុខ្ពស់',
  'tools.newest': 'ថ្មីជាងគេ',
  'tools.noResults': 'រកឧបករណ៍មិនឃើញ។ សូមសាកល្អកាស។',

  'tool.try': 'សាក',
  'tool.run': 'ដំណើរការ',
  'tool.running': 'កំពុងដំណើរការ...',
  'tool.result': 'លទ្ធផល',
  'tool.reviews': 'មតិ',
  'tool.dailyLimit': 'ដែនកំណត់ប្រចាំថ្ងៃ',
  'tool.usedToday': 'ប្រើថ្ងៃនេះ',
  'tool.remainingToday': 'នៅសល់ថ្ងៃនេះ',
  'tool.unlimited': 'មិនកំណត់',
  'tool.signUpToUse': 'ចុះឈ្មោះដើម្បីប្រើ',
  'tool.upgradeToPro': 'អាន់គ្រេតទៅ Pro',
  'tool.buyNow': 'ទិញឥឡូវនេះ',
  'tool.purchased': 'បានទិញរួច',
  'tool.backToTools': 'ត្រឡប់ទៅឧបករណ៍',

  'auth.login.title': 'ចូល',
  'auth.signup.title': 'បង្កើតគណនី',
  'auth.login.welcome': 'សូមស្វាគមន៍ត្រឡប់មក EDU',
  'auth.signup.welcome': 'ចាប់ផ្តើមរៀនបានឆ្លាតថ្ងៃនេះ',
  'auth.login.subtitle': 'សូមស្វាគមន៍ត្រឡប់! សូមបញ្ចូលព័ត៌មានរបស់អ្នក។',
  'auth.signup.subtitle': 'ដោយឥតគិតដល់ត្រីយ។ អាន់គ្រេតនៅពេលណាក៏បាន។',
  'auth.email': 'អ៊ីមែល',
  'auth.password': 'ពាក្យសម្ងាត់',
  'auth.fullName': 'ឈ្មោះពេញ',
  'auth.signIn': 'ចូល',
  'auth.createAccount': 'បង្កើតគណនី',
  'auth.orContinue': 'ឬបន្តជាមួយ',
  'auth.haveAccount': 'មិនទាន់មានគណនី?',
  'auth.noAccount': 'មានគណនីរួចហើយ?',

  'dashboard.title': 'ផ្ទាំងគ្រប់គ្រង',
  'dashboard.welcome': 'សូមស្វាគមន៍ត្រឡប់',
  'dashboard.totalUses': 'ប្រើ AI សរុប',
  'dashboard.usedToday': 'ប្រើថ្ងៃនេះ',
  'dashboard.favorites': 'ចំណូលចិត្ត',
  'dashboard.recentlyUsed': 'បានប្រើថ្មីៗ',
  'dashboard.favoriteTools': 'ឧបករណ៍ចំណូលចិត្ត',
  'dashboard.notifications': 'ការជូនដំណឹង',
  'dashboard.upgradeBanner': 'ដោះស្រាយ AI មិនកំណត់',
  'dashboard.upgradeDesc': 'អាន់គ្រេតទៅ Pro សម្រាប់ការប្រើមិនកំណត់ ឧបករណ៍ពិសេស និងគាំទ្រអាទិភាព។',
  'dashboard.seePlans': 'មើលផែនការ',
  'dashboard.proMember': 'សមាជិក Pro',
  'dashboard.upgradeToPro': 'អាន់គ្រេតទៅ Pro',

  'admin.title': 'ផ្ទាំងគ្រប់គ្រងអេដមីន',
  'admin.overview': 'ទិដ្ឋភាពទូទៅ',
  'admin.tools': 'ឧបករណ៍',
  'admin.resources': 'ធនធាន',
  'admin.users': 'អ្នកប្រើ',
  'admin.purchases': 'ការទិញ',
  'admin.totalUsers': 'អ្នកប្រើសរុប',
  'admin.totalTools': 'ឧបករណ៍សរុប',
  'admin.totalResources': 'ធនធានសរុប',
  'admin.totalRevenue': 'ប្រាក់ចំណូលសរុប',
  'admin.addTool': 'បន្ថែមឧបករណ៍',
  'admin.editTool': 'កែសម្រួលឧបករណ៍',
  'admin.addResource': 'បន្ថែមធនធាន',
  'admin.editResource': 'កែសម្រួលធនធាន',
  'admin.toolName': 'ឈ្មោះឧបករណ៍',
  'admin.toolSlug': 'Slug',
  'admin.toolIcon': 'រូបតំណាង',
  'admin.toolCategory': 'ប្រភេទ',
  'admin.toolIsPro': 'ឧបករណ៍ Pro',
  'admin.toolUsageLimit': 'ដែនកំណត់ដោយឥតគិត',
  'admin.toolPrice': 'តម្លៃ (USD)',
  'admin.toolRating': 'ពិន្ទុ',
  'admin.toolReviews': 'ចំនួនមតិ',
  'admin.resourceName': 'ឈ្មោះធនធាន',
  'admin.resourceType': 'ប្រភេទ',
  'admin.resourceCategory': 'ប្រភេទ',
  'admin.resourceImage': 'URL រូបភាព',
  'admin.resourceIsPremium': 'ពិសេស',
  'admin.userEmail': 'អ៊ីមែល',
  'admin.userPlan': 'ផែនការ',
  'admin.userRole': 'តួនាទី',
  'admin.makeAdmin': 'តែងអេដមីន',
  'admin.makeUser': 'តែងអ្នកប្រើ',
  'admin.makePro': 'តែង Pro',
  'admin.makeFree': 'តែង Free',
  'admin.purchaseItem': 'ផលិតផល',
  'admin.purchaseAmount': 'ចំនួន',
  'admin.purchaseMethod': 'វិធីសាស្ត្រ',
  'admin.purchaseDate': 'កាលបរិច្ឆេទ',
  'admin.confirmDelete': 'តើអ្នកប្រាកដថាចង់លុបវាឬ?',
  'admin.accessDenied': 'បដិសេធ! សម្រាប់អេដមីនប៉ុណ្ណោះ។',
  'admin.saved': 'រក្សាទុកបានជោគជ័យ!',
  'admin.deleted': 'លុបបានជោគជ័យ!',

  'payment.title': 'បញ្ចប់ការទិញរបស់អ្នក',
  'payment.cardNumber': 'លេខកាត',
  'payment.cardName': 'ឈ្មោះម្ចាស់កាត',
  'payment.expiry': 'ថ្ងៃផុតកំណត់',
  'payment.cvv': 'CVV',
  'payment.payNow': 'បង់ឥឡូវ',
  'payment.processing': 'កំពុងដំណើរការ...',
  'payment.success': 'បង់ប្រាក់បានជោគជ័យ!',
  'payment.cardNumberPlaceholder': '1234 5678 9012 3456',
  'payment.cardNamePlaceholder': 'JOHN DOE',
  'payment.expiryPlaceholder': 'MM/YY',
  'payment.cvvPlaceholder': '123',
  'payment.total': 'សរុប',
  'payment.secure': 'ការបង់ប្រាក់របស់អ្នកមានសុវត្ថិភាពជាមួយការអ៊ីនគ្រីប 256-bit',

  'pricing.title': 'ជ្រើសរើសផែនការរបស់អ្នក',
  'pricing.subtitle': 'ចាប់ផ្តើមដោយឥតគិត អាន់គ្រេតនៅពេលអ្នកត្រៀម។ មិនមានថ្លៃលាក់ បោះបង់នៅពេលណាក៏បាន។',
  'pricing.badge': 'តម្លៃសាមញ្ញ តម្លៃច្បាស់លាស់',
  'pricing.guest': 'ភ្ញៀវ',
  'pricing.free': 'ដោយឥតគិត',
  'pricing.pro': 'Pro',
  'pricing.popular': 'ពេញនិយម',
  'pricing.currentPlan': 'ផែនការបច្ចុប្បន្ន',
  'pricing.payments': 'វិធីបង់ប្រាក់ដែលទទួលយក',
  'pricing.paymentsDesc': 'អាន់គ្រេតពី Free ទៅ Pro ដោយសុវត្ថិភាពជាមួយវិធីបង់ប្រាក់ដែលអ្នកចង់ប្រើ',
  'pricing.continueWith': 'បន្តជាមួយ',
  'pricing.demoNote': 'សម្រាប់បង្ហាញតែ — ការតភ្ជាប់បង់ប្រាក់ត្រូវការការកំណត់ផ្តល់ការ។',

  'footer.tagline': 'វេទិកាអប់រំដែលមាន AI ទាំងអស់ក្នុងមួយ។ រៀន បង្កើត និងរីកចម្រើនជាមួយឧបករណ៍ AI ដែលមានឥទ្ធិពល។',
  'footer.platform': 'វេទិកា',
  'footer.account': 'គណនី',
  'footer.company': 'ក្រុមហ៊ុន',
  'footer.rights': 'រក្សាសិទ្ធិទាំងអស់។',
  'footer.built': 'អភិវឌ្ឍដោយក្រុមនិស្សិត IT។',

  'stats.tools': 'ឧបករណ៍ AI',
  'stats.resources': 'ធនធាន',
  'stats.students': 'សិស្ស',
  'stats.countries': 'ប្រទេស',
  'stats.purchases': 'ការទិញ',
  'stats.revenue': 'ប្រាក់ចំណូល',

  'feature.aiLearning.title': 'ការរៀនដោយ AI',
  'feature.aiLearning.desc': 'ឧបករណ៍ AI ជាង ១៦ ប្រភេទ ដែលជួយឲ្យអ្នកសិក្សា សរសេរ កូដ និងស្រាវជ្រាវ។',
  'feature.aiLearning.cta': 'ស្វែងរកឧបករណ៍ AI',
  'feature.resources.title': 'ធនធានសម្បូរបែប',
  'feature.resources.desc': 'វគ្គសិក្សា សៀវភៅអេឡិចត្រូនិក វីដេអូ និងលំហាត់ — ទាំងអស់ក្នុងមួយកន្លែង។',
  'feature.resources.cta': 'មើលធនធាន',
  'feature.fast.title': 'លឿន និងទៀងទាត់',
  'feature.fast.desc': 'បង្កើនប្រសិទ្ធភាពភាពលឿន ជាមួយការឆ្លើយតប AI ភ្លាមៗ និង UX រលូន។',
  'feature.fast.cta': 'សាកជំនួយការ AI',
  'feature.secure.title': 'សុវត្ថិភាព និងឯកជន',
  'feature.secure.desc': 'សុវត្ថិភាពកម្រិតជួរ ការផ្ទៀងផ្ទាត់ JWT និងការរក្សាទុកទិន្នន័យដោយអ៊ីនគ្រីប។',
  'feature.secure.cta': 'មើលតម្លៃ',
  'feature.multilang.title': 'គាំទ្រច្រើនភាសា',
  'feature.multilang.desc': 'រចនាសម្ព័ន្ធសម្រាប់ខ្មែរ អង់គ្លេស ថៃ និងវៀតណាម។',
  'feature.multilang.cta': 'ចាប់ផ្តើម',
  'feature.pro.title': 'បទពិសោធន៍ Pro',
  'feature.pro.desc': 'ដោះស្រាយការប្រើមិនកំណត់ ឧបករណ៍ពិសេស និងគាំទ្រអាទិភាព។',
  'feature.pro.cta': 'មើលផែនការ',

  'auth.google': 'Google',
  'auth.googleError': 'ការចូលជាមួយ Google បរាជ័យ។ សូមព្យាយាមម្តងទៀត។',
  'auth.forgotPassword': 'ភ្លេចពាក្យសម្ងាត់?',
  'auth.resetPassword': 'ផ្ញើតំណភ្ជាប់ប្ដូរពាក្យសម្ងាត់',
  'auth.resetSent': 'តំណភ្ជាប់ប្ដូរពាក្យសម្ងាត់បានផ្ញើទៅអ៊ីមែលរបស់អ្នក!',

  'admin.code.title': 'លេខកូដចូលអេដមីន',
  'admin.code.desc': 'សូមបញ្ចូលលេខកូដអេដមីនដើម្បីបន្ត។',
  'admin.code.placeholder': 'បញ្ចូលលេខកូដអេដមីន',
  'admin.code.verify': 'ផ្ទៀងផ្ទាត់',
  'admin.code.invalid': 'លេខកូដអេដមីនមិនត្រឹមត្រូវ។ សូមព្យាយាមម្តងទៀត។',
  'admin.code.verifying': 'កំពុងផ្ទៀងផ្ទាត់...',
  'admin.testimonials': 'មតិសិស្ស',
  'admin.content': 'មាតិកា',
  'admin.addTestimonial': 'បន្ថែមមតិ',
  'admin.editTestimonial': 'កែសម្រួលមតិ',
  'admin.testimonialName': 'ឈ្មោះសិស្ស',
  'admin.testimonialRole': 'តួនាទី / ចំណងជើង',
  'admin.testimonialAvatar': 'URL រូបភាព',
  'admin.testimonialText': 'មាតិកាមតិ',
  'admin.testimonialRating': 'ពិន្ទុ (១-៥)',
  'admin.changeCode': 'ប្ដូរលេខកូដអេដមីន',
  'admin.newCode': 'លេខកូដអេដមីនថ្មី',
  'admin.codeChanged': 'លេខកូដអេដមីនបានផ្លាស់ប្ដូរជោគជ័យ!',
  'admin.totalPurchases': 'ការទិញសរុប',

  'contact.name': 'ឈ្មោះ',
  'contact.email': 'អ៊ីមែល',
  'contact.message': 'សារ',
  'contact.namePlaceholder': 'ឈ្មោះរបស់អ្នក',
  'contact.emailPlaceholder': 'you@example.com',
  'contact.messagePlaceholder': 'យើងអាចជួយអ្វីបាន?',
  'contact.send': 'ផ្ញើសារ',
  'contact.sent': 'បានផ្ញើ!',
  'contact.info.email': 'អ៊ីមែល',
  'contact.info.phone': 'ទូរស័ព្ទ',
  'contact.info.address': 'អាសយដ្ឋាន',
  'contact.info.emailValue': 'Khouvchvea123@gmail.com',
  'contact.info.phoneValue': '+855 97 8114 331',
  'contact.info.addressValue': 'ភ្នំពេញ ប្រទេសកម្ពុជា',
  'contact.payments': 'វិធីបង់ប្រាក់ដែលទទួលយក',

  'faq.q1': 'EDU ជាអ្វី?',
  'faq.a1': 'EDU ជាវេទិកាអប់រំដែលមាន AI ទាំងអស់ក្នុងមួយ ដែលសិស្សអាចរៀន ចូលប្រើធនធានអប់រំ និងប្រើឧបករណ៍ AI ដែលមានឥទ្ធិពល។',
  'faq.q2': 'តើ EDU ប្រើដោយឥតគិតទេឬ?',
  'faq.a2': 'បាទ! ផែនការដោយឥតគិតឲ្យអ្នកប្រើ AI កំណត់ប្រចាំថ្ងៃ និងចូលប្រើមាតិកាអប់រំដោយឥតគិត។ អាន់គ្រេតទៅ Pro សម្រាប់ការប្រើមិនកំណត់ និងមុខងារពិសេស។',
  'faq.q3': 'តើផែនការ Pro មានអ្វីខ្លះ?',
  'faq.a3': 'Pro រួមមានការប្រើ AI មិនកំណត់ ឧបករណ៍ និងវគ្គសិក្សាពិសេស ការឆ្លើយតបលឿន គាំទ្រអាទិភាព ប្រវត្តិក្នុងពពក និងមុខងារកម្រិតខ្ពស់។',
  'faq.q4': 'តើអាចបោះបង់ការត្រិតត្រូវបាននៅពេលណាឬ?',
  'faq.a4': 'បាទជាក់ជាក។ អ្នកអាចបោះបង់ការត្រិតត្រូវ Pro នៅពេលណាក៏បាន និងបន្តប្រើមុខងារផែនការដោយឥតគិត។',
  'faq.q5': 'តើត្រូវបង្កើតគណនីទេ?',
  'faq.a5': 'ភ្ញៀវអាចមើលឧបករណ៍ និងធនធានបាន។ ដើម្បីប្រើឧបករណ៍ AI និងរក្សាទុកចំណូលចិត្ត សូមបង្កើតគណនីដោយឥតគិត។',
  'faq.q6': 'តើគាំទ្រវិធីបង់ប្រាក់អ្វីខ្លះ?',
  'faq.a6': 'យើងគាំទ្រ ABA Pay, KHQR, Visa/MasterCard, PayPal, និង Stripe សម្រាប់ការអាន់គ្រេតសុវត្ថិភាព។',

  'pricing.guestDesc': 'សម្រាប់ភ្ញៀវដែលចង់ដឹង',
  'pricing.freeDesc': 'សម្រាប់សិស្សដែលទើបចាប់ផ្តើម',
  'pricing.proDesc': 'សម្រាប់អ្នករៀនពិតជា',
  'pricing.guestFeatures': 'មើលឧបករណ៍ AI, មើលធនធានអប់រំ, អានមតិសិស្ស',
  'pricing.freeFeatures': 'ការប្រើ AI កំណត់ប្រចាំថ្ងៃ, ចូលប្រើមាតិកាដោយឥតគិត, រក្សាទុកចំណូលចិត្ត, ផ្ទាំងគ្រប់គ្រងផ្ទាល់ខ្លួន, ចូលប្រើសហគមន៍',
  'pricing.proFeatures': 'ការប្រើ AI មិនកំណត់, ឧបករណ៍ AI ពិសេសទាំងអស់, វគ្គសិក្សា និងធនធានពិសេស, ការឆ្លើយតប AI លឿន, គាំទ្រអាទិភាព, ប្រវត្តិក្នុងពពក, មុខងារកម្រិតខ្ពស់',
  'pricing.signUpFree': 'ចុះឈ្មោះដោយឥតគិត',
  'pricing.upgradeToPro': 'អាន់គ្រេតទៅ Pro',
  'pricing.browseTools': 'មើលឧបករណ៍',
  'pricing.trustSecure': 'ការបង់ប្រាក់សុវត្ថិភាព',
  'pricing.trustSecureDesc': 'អ៊ីនគ្រីប 256-bit លើរាល់ប្រតិបត្តិការ',
  'pricing.trustInstant': 'ចូលប្រើភ្លាមៗ',
  'pricing.trustInstantDesc': 'មុខងារ Pro ដំណើរការភ្លាមៗ',
  'pricing.trustCancel': 'បោះបង់នៅពេលណាក៏បាន',
  'pricing.trustCancelDesc': 'មិនមានកិច្ចព្រមព្រៀងរយៈពេលវែង មិនមានបញ្ហា',
};

const dictionaries: Record<Language, Dict> = { en, km };

interface LanguageContextValue {
  lang: Language;
  setLang: (l: Language) => void;
  toggleLang: () => void;
  t: (key: string, vars?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'en';
    return (localStorage.getItem('edu-lang') as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('edu-lang', lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const setLang = (l: Language) => setLangState(l);
  const toggleLang = () => setLangState((l) => (l === 'en' ? 'km' : 'en'));

  function t(key: string, vars?: Record<string, string | number>): string {
    let str = dictionaries[lang][key] ?? dictionaries.en[key] ?? key;
    if (vars) {
      for (const [k, v] of Object.entries(vars)) {
        str = str.replace(`{${k}}`, String(v));
      }
    }
    return str;
  }

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used within LanguageProvider');
  return ctx;
}
